<br/>
<EMBED
src="http://service.weibo.com/staticjs/weiboshow.swf?verifier=ef835547&uid=2586744222&width=220&height=400&isTitle=0&isWeibo=1&isFans=0&noborder=1&ptype=1&colors=ffffff,ffffff,444444,5093d5"
quality="high" width="220" height="400" align="C" scale="noborder"
flashvars="width=220&height=400&uid=2586744222&skin=skin1"
allowScriptAccess="sameDomain"
type="application/x-shockwave-flash"></EMBED>